include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

formatter:
  page_width: 120

linter:
  rules:
    - always_declare_return_types
    - public_member_api_docs
